### PR TITLE
Fix NULL handling for OptionalFieldProperty and OptionalEnumProperty

### LINKED ISSUE #396: Model + CRUD: Order of the elements should not matter when CREATE is called on a collection.
## Description
If we are calling create on a collection of models, depending on the order of collection either an error is thrown or the value is set incorrectly without any error being thrown. For example, the below collection incorrectly set the enum value to `null` and does not throw any error.

```swift
func prepare(on database: Database) -> EventLoopFuture<Void> {
        let workouts = [
            Workout(name: "Walking", duration: 30, distance: 2.5, effort: nil),
            Workout(name: "Running", duration: 30, distance: 4.0, effort: nil),
            Workout(name: "Biking", duration: 30, distance: 5.25, effort: nil),
            Workout(name: "Swimming", duration: 30, distance: 3.5, effort: nil),
            Workout(name: "Yoga", duration: 30, distance: nil, effort: .moderate)
        ]
        return workouts.create(on: database)
    }
```

Here is the debug log for the above code.
```
INSERT INTO "workouts" ("name", "durartionInMinutes", "distanceInKilometers", "id") VALUES ($1, $2, $3, DEFAULT), ($4, $5, $6, DEFAULT), ($7, $8, $9, DEFAULT), ($10, $11, $12, DEFAULT), ($13, $14, NULL, DEFAULT) RETURNING "id" ["Walking", 30.0, 2.5, "Running", 30.0, 4.0, "Biking", 30.0, 5.25, "Swimming", 30.0, 3.5, "Yoga", 30.0]
```

However, if we set the optional enum value in the first item of the collection and do not set it for the rest then it throws the below error. 
``` swift 
func prepare(on database: Database) -> EventLoopFuture<Void> {
        let workouts = [
            Workout(name: "Yoga", duration: 30, distance: nil, effort: .moderate),
            Workout(name: "Walking", duration: 30, distance: 2.5, effort: nil),
            Workout(name: "Running", duration: 30, distance: 4.0, effort: nil),
            Workout(name: "Biking", duration: 30, distance: 5.25, effort: nil),
            Workout(name: "Swimming", duration: 30, distance: 3.5, effort: nil)
        ]
        return workouts.create(on: database)
    }
```

```
NIO-ELT-0-#3 (5): Fatal error: Non-uniform query input: [[id: default, name: "Yoga", effort: moderate, distance_in_kilometers: nil, durartionInMinutes: 30.0], [id: default, durartion_in_minutes: 30.0, name: "Walking", distanceInKilometers: Optional(2.5)], [id: default, name: "Running", durartionInMinutes` 
```

### Model
```swift
final class Workout: Model, Content {
    static let schema = SchemaConstants.workout
    
    @ID(custom: "id", generatedBy: .database)
    var id: Int?
    
    @Field(key: "name")
    var name: String
    
    @Field(key: "durartion_in_minutes")
    var duration: Double
    
    @Field(key: "distance_in_kilometers")
    var distance: Double?
    
    @OptionalEnum(key: "effort")
    var effort: EffortType?
    
    init() {}
    
    init(id: Int? = nil,
         name: String,
         duration: Double,
         distance: Double?,
         effort: EffortType? = nil) {
        self.id = id
        self.name = name
        self.duration = duration
        self.distance = distance
        self.effort = effort
    }
}
```
### Migration
```swift
struct CreateWorkout: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        return database.schema(SchemaConstants.workout)
            .field("id", .int, .identifier(auto: true))
            .field("name", .string, .required)
            .field("durartion_in_minutes", .double, .required)
            .field("distance_in_kilometers", .double)
            .unique(on: "name")
            .create()
            .map { res in
                return res
        }.flatMap { _ in
            database.enum("effort_type")
                .read()
                .flatMap { efforts in
                database.schema(SchemaConstants.workout)
                    .field("effort", efforts)
                    .update()
            }
        }.transform(to: ())
    }
    
    func revert(on database: Database) -> EventLoopFuture<Void> {
        return database.schema(SchemaConstants.workout).delete()
    }
}
```

### LINKED ISSUE #444: Cannot update value of an @OptionalEnum field to nil
I attempt to update a field defined as an @OptionalEnum to **nil**. The field value does not change. Changing the value to other values of the enum **does** work correctly.

I have also seen this error with other optional fields, i.e. I can update the field to other values, but not to nil

I have shown this to Tim Condon who showed me how to see the error occurring in the debug log, shown below.

### To Reproduce

**FIELD DEFINITION:**	
	@OptionalEnum(key: "playerRequest")
	var playerRequest: PlayerRequestType?

**CODE TO SET OPTIONAL ENUM TO NIL:**
	sportPlayerPivotForPlayerOut.playerStatus = .notPlaying
	sportPlayerPivotForPlayerOut.playerRequestComments = "removed by organiser"
	**sportPlayerPivotForPlayerOut.playerRequest = nil**	//TIM??? !!!	not working
	sportPlayerPivotForPlayerOut.$currentLeague.id = nil
	sportPlayerPivotForPlayerOut.leagueNumber = nil
	let update2 = sportPlayerPivotForPlayerOut.update(on: req.db)
	updates.append(update2)

DEBUG TRACE SHOWING VALUE -NOT- UPDATED:

[ DEBUG ] query update sport_player_pivots filters=[sport_player_pivots[id] = 466EFFB4-8DD7-4812-A66F-29D048E20B49] input=[[playerStatus: notPlaying, dateModified: "2021-07-20T10:38:29Z", leagueNumber: nil, playerRequestComments: "removed by organiser", **playerRequest: remain**, currentLeagueID: nil]] [database-id: psql, request-id: 6BD2882E-DAB7-4985-A1A6-9803B4C59E3D] (FluentKit/Query/Builder/QueryBuilder.swift:297)

1. Add package with configuration '...'
2. Send request with options '...'
3. See error

### Expected behavior

Field value updated to nil

### Environment

Using **postgres**
framework: 4.48.0
toolbox: 18.3.2

* OS version:

11.4

### PR DESCRIPTION
**Pull request by gwynne**
`OptionalFieldProperty.value.getter` was incorrectly returning `.none(.none)` instead of `.some(.none)` when `self.inputValue` was `DatabaseQuery.Value.null`, preventing explicitly set `nil` values set by properties that wrap optional field properties (i.e. `OptionalEnumProperty`) from taking effect as they should.

Additionally, `OptionalEnumProperty.value.setter` was not correctly forwarding the double-optional state of `newValue`, causing a `fatalError()` due to non-uniform input sets on bulk inserts.

This fixes both of those issues and updates the appropriate tests. The behavior of `OptionalEnumProperty` is noticeably different now, so even though this does not change any public API, it will be released as `semver-minor` to lessen impact for those who were relying on the incorrect old behavior.

Fixes #396.
Fixes #444.

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]

**Comment by jaredh159** [comment]
@gwynne spent a little time trying to test this fix, as requested, but am struggling as to how to pull in the new code.  I tried depending on a branch and a commit in my `Package.swift` (even though my project doesn't explicitly depend on `fluent-kit`, only on `fluent`), but I kept running into errors.

Is there a simpler way to test out a patch like this in a local vapor app?

**Comment by 0xTim** [comment]
You can checkout FluentKit and run it in a workspace as described here https://www.timc.dev/posts/editing-swift-packages/

Alternatively depending on the branch _should_ work - how are you defining it? (Option 1 is much easier)

**Comment by jaredh159** [comment]
@0xTim struggling to follow the instructions in your post.  Admittedly, Xcode and me are not the best of friends, I try to do almost all of my Swift development in vscode.  The part of your instructions where you say "find the directory for the package you want to work on and drag that directory into the project navigator in Xcode" -- I'm a bit lost on.  I created an empty workspace. Do I then open a finder window and drag the root folder of my vapor App into the left-hand side of Xcode?  I tried that, but it didn't look like your screenshot, and Xcode didn't seem to notice the `Package.swift` file or do any fetching of dependencies or anything like that.  Am I misunderstanding your instructions?  Sorry for being such an Xcode noob.

**Comment by 0xTim** [comment]
@jaredh159 yeah that's correct, in the workspace just drop the directory containing the package.swift into the bar and then drop the dependency you want to edit. The screenshots may be out of date with Xcode 12

**Comment by gwynne** [comment]
I'm going to go ahead and merge these changes, hopefully they do solve the issue in question. If not, ping me on Discord and I'll have another look.

**Pull request merged**
