### PR TITLE
Fix mysql SQLDropConstraint CONSTRAINT serialize

### PR DESCRIPTION
**Pull request by kevinzhow**
fix https://github.com/vapor/fluent/issues/722 and https://github.com/vapor/fluent-kit/issues/491

### CODE REVIEW

**Comment by 0xTim** [comment]
This looks OK to me but I don't know enough about MySQL to say what is the correct approach. I'll leave it to Gwynne. It may be that different versions require different dialects

**Comment by kevinzhow** [comment]
> This looks OK to me but I don't know enough about MySQL to say what is the correct approach. I'll leave it to Gwynne. It may be that different versions require different dialects

you were right, the old work around is for mysql 5.7, but....
after I testing the old work around it on mysql 5.7, it also result in issue.

according to [MySQL Reference](https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html)

```
Dropping Foreign Key Constraints

You can drop a foreign key constraint using the following [ALTER TABLE](https://dev.mysql.com/doc/refman/5.7/en/alter-table.html) syntax:


ALTER TABLE tbl_name DROP FOREIGN KEY fk_symbol;
```

When to MySQL 5.7, it should be `FOREIGN KEY`
MySQL 8.0 and later, it should be `CONSTRAINT`

**Comment by bottlehall** [comment]
Is there any chance of fixing this? My original issue  [722](https://github.com/vapor/fluent/issues/722 remains and it makes unit-testing very tedious as you can't revert the database automatically.

**Comment by gwynne** [comment]
@bottlehall #522 should have solved this issue. Are you still running into it?

**Comment by bottlehall** [comment]
Hi Gwynne

\Yes, I’ve just created a minimal migration/reversion and it still happens. It fails with a MySQL error:

testIndex(): failed: caught error: "MySQL error: Server error: Cannot drop column 'defaultUnitId': needed in a foreign key constraint '864a4b794b34ca99a50c05a6504fa9f21b839e9a’"

This is the field that was added in the migration and the constraint is created during the migration. 

    struct UpdateUserTable2: AsyncMigration {
        func prepare(on database: Database) async throws {
            try await database.schema("User")
                .field("defaultUnitId", .uuid, .references("Unit", "id"))
                .update()
        }

        func revert(on database: Database) async throws {
            try await database.schema("User")
                .deleteField("defaultUnitId")
                .update()
        }
    }

I have checked that the same error arises if I use the alternative method of creating the foreign key:

.foreignKey("createdByUserId", references: "User", "id", name: "created_user_id”)

And reverting using:

.deleteConstraint(name: "created_user_id")

Before trying to delete the field.

Best wishes

Nick

**Comment by gwynne** [comment]
Support for the missing functionality and information regarding its use has been added in #575

**Pull request closed without merging**
