### PR TITLE
Beta 5

### PR DESCRIPTION
**Pull request by tanner0101**
> Important, breaking changes highlighted with ⚠️.

### Adds top-level `FieldKey` type (#165)

Adds a new top-level `FieldKey` type to FluentKit. This type represents possible field key values but in a slightly more type-safe way than `String` is currently able to. 

The basic structure of `FieldKey` is a String literal expressible enum:

```swift
public enum FieldKey: ExpressibleByStringLiteral {
    case id
    case string(String)
}
```

`FieldKey` is usable everywhere String keys were previously usable, including property wrappers, filter expressions, and schema builders.

`FieldKey`  can be extended by the end user. This could be a good solution to keeping String key declarations DRY. For example:

```swift
extension FieldKey {
    static var name: Self { "name" }
}
```

The new special `id` case should be used with the `@ID` property wrapper. The strings `"id"` and `"_id"` will both convert automatically to the special `.id` field key for backward compatibility.

⚠️ By default, `@ID` will now require the `.id` field key as well as `UUID` value. This allows for your models to support all of Fluent's drivers by default. This includes MongoDB.

There is a new syntax for using custom IDs:

```swift
@ID(custom: "foo", generatedBy: .user)
var id: String?
```

This syntax change is intended to push users toward declaring models that work with all drivers while still allowing usage of custom ID keys and types with limited driver support.

A new helper method for generating a default id column has been added to the schema builder:

```swift
database.schema("planets")
    .id()
    .field(...)
    ...
    .create()
```

### Adds `@Enum` for using native database enums (#178).

Adds native enum support. This includes a new `@Enum` property, `database.enum(_:)` builder, and support for modifying a field's data type. 

```swift
enum Bar: String, Codable {
    case baz, qux
}
```

Native database enums must be String backed since they are serialized directly to the query.

```swift
final class Foo: Model {
    static let schema = "foos"

    @ID(key: .id)
    var id: UUID?

    @Enum(key: "bar")
    var bar: Bar
}
```

If you are using a database with schemas, native enums must be registered using the new `database.enum` builder. This will create a data type that you can pass into the normal schema builder for the given field.

```swift
struct FooMigration: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.enum("bar")
            .case("baz")
            .case("qux")
            .create()
            .flatMap
        { bar in
            database.schema("foos")
                .field("id", .uuid, .identifier(auto: false))
                .field("bar", bar, .required)
                .create()
        }
    }

    func revert(on database: Database) -> EventLoopFuture<Void> {
        database.schema("foos").delete().flatMap {
            database.enum("bar").delete()
        }
    }
}
```

Adding cases to an enum is also supported:

```swift
enum Bar: String, Codable {
    case baz, qux, quuz
}
```

A migration is required to update the database:

```swift
struct BarAddQuuzMigration: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.enum("bar")
            .case("quuz")
            .update()
            .flatMap
        { bar in
            database.schema("foos")
                .updateField("bar", bar)
                .update()
        }
    }

    func revert(on database: Database) -> EventLoopFuture<Void> {
        database.enum("bar")
            .deleteCase("quuz")
            .update()
            .flatMap
        { bar in
            database.schema("foos")
                .updateField("bar", bar)
                .update()
        }
    }
}
```

Enum metadata is stored in the `_fluent_enums` schema. 

### Adds `@CompoundField` for storing nested fields as a flat, top-level fields in the database (#176).

This new property wrapper allows for a collection of fields to be stored as top-level keys in the database.

To use this feature, first declare a type representing the desired field structure conforming to `Fields`:

```swift
final class Pet: Fields {
    @Field(key: "name")
    var name: String

    @Field(key: "type")
    var type: Animal
}
```

Next, declare a `@CompoundField` on your model that uses this type.

```swift
final class User: Model {
    ...

    @CompoundField(key: "pet")
    var pet: Pet
}
```

This will result in `Pet`'s fields being stored as top-level fields prefixed by `"pet_"` in the database, as can be seen by the migration:

```swift
struct UserMigration: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.schema("users")
            .field("id", .uuid, .identifier(auto: false))
            .field("name", .string, .required)
            .field("pet_name", .string, .required)
            .field("pet_type", .string, .required)
            .create()
    }

    func revert(on database: Database) -> EventLoopFuture<Void> {
        database.schema("users").delete()
    }
}
```

Compound fields can be accessed and queried from Swift using dot-syntax:

```swift
print(user.pet.name)
User.query(on: db).filter(\.$pet.$type == .cat)
```

Thanks to @Joannis and @calebkleveter for discovering how to do nested key paths! 

### Adds `@NestedField` for storing a collection of fields as a nested object in the database (#177). 

`@NestedField` works similarly to `@CompoundField` except the fields are stored as a nested object in the database, not top-level keys. 

This is reflected in migrations which should use the `.json` data type for `@NestedField` instead of many top-level fields for `@CompoundField`:

Replacing the `@CompoundField` example with `@NestedField` would require the following migration:

```swift
final class User: Model {
    ...

    @NestedField(key: "pet")
    var pet: Pet
}
```

```swift
private struct UserMigration: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.schema("users")
            .field("id", .uuid, .identifier(auto: false))
            .field("name", .string, .required)
            .field("pet", .json, .required)
            .create()
    }

    func revert(on database: Database) -> EventLoopFuture<Void> {
        database.schema("users").delete()
    }
}
```

### `DatabaseQuery` aggregates have been refactored to be easier to implement in drivers (#171).

This change is mostly internal, except that `FieldRepresentable` has been split into two protocols named `QueryField` and `FilterField`. All fields that have a single key, like `@ID`, `@Field`, and `@Parent` are query fields. Filter fields are a special case of field that have a key _path_, like `@NestedField`. Filter fields may only be used with query builder operations that result in filters.

### `Set` is now compatible with the `.array` database type (#170).

```swift
final class User: Model {
    @ID(key: .id)
    var id: UUID?

    @Field(key: "roles")
    var roles: Set<UserRole>
}
```

```swift
struct UserMigration: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.schema("users")
            .id()
            .field("roles", .array(of: .string), .required)
            .create()
    }

    func revert(on database: Database) -> EventLoopFuture<Void> {
        database.schema("users").delete()
    }
}
```

### `MigrationLog` renamed and uses `UUID` id for compatibility with MongoDB (#172). 

⚠️ This is a breaking change for Vapor 4 databases with pre-existing migrations. Dropping your database and re-running migrations will generate the new log table correctly. To upgrade an existing log table while maintaining the data, you can use the following scripts:

**MySQL**
```sql
ALTER TABLE `fluent` DROP COLUMN `id`;
ALTER TABLE `fluent` ADD `id` VARBINARY(16);
UPDATE `fluent` SET `id` = uuid_to_bin(uuid());
ALTER TABLE `fluent` MODIFY COLUMN `id` VARBINARY(16) PRIMARY KEY;
RENAME TABLE `fluent` TO `_fluent_migrations`;
```

**PostgreSQL**
```sql
CREATE extension IF NOT EXISTS "uuid-ossp";
ALTER TABLE "fluent" DROP COLUMN "id";
ALTER TABLE "fluent" ADD "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4();
ALTER TABLE "fluent" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "fluent" RENAME TO "_fluent_migrations"
```

It is not possible to update a pre-existing SQLite database since SQLite does not expose a method for generating UUIDs. 

### `FluentBenchmarker` has been refactored to improve testing on all supported drivers (#170).

This change makes it easier to test drivers as well as ensuring that all benchmarker tests, even newly added ones, are running correctly. 

### Refactor `DatabaseConfiguration` and implement `Databases.reinitialize(_:)` (#174, #175).

This change is mostly an internal improvement to Fluent's database configuration code. It also allows for databases to be reinitialized, causing all open connections to be refreshed. 

```swift
// Default database.
app.dbs.reinitialize()
// By database id.
app.dbs.reinitialize(.psql)
```

### Improved `ModelAlias` support (#180).

`ModelAlias` is now more easily usable when building queries. It can be used anywhere a `Model` can be used.

The definition of a model alias has changed slightly to become:

```swift
final class HomeTeam: ModelAlias {
    static let name = "home_teams"
    let model = Team()
}
final class AwayTeam: ModelAlias {
    static let name = "away_teams"
    let model = Team()
}
```

Methods like `filter` and `sort` are now easier to use with aliases:

```swift
let matches = try Match.query(on: self.database)
    .join(HomeTeam.self, on: \Match.$homeTeam.$id == \HomeTeam.$id)
    .join(AwayTeam.self, on: \Match.$awayTeam.$id == \AwayTeam.$id)
    .filter(HomeTeam.self, \.$name == "a")
    .sort(AwayTeam.self, \.$name)
    .all().wait()

for match in matches {
    let home = try match.joined(HomeTeam.self)
    let away = try match.joined(AwayTeam.self)
    ...
}
```

### CODE REVIEW

**Comment by 0xTim** [comment]
Making models only work with the ID name of `id` will make it impossible for some existing databases to be Fluent compatible. Locking it down to that extent would be the wrong decision IMO. It also complicates migrating from Fluent 3 to Fluent 4 for anyone who used an ID key of anything other than `id`. 

Is there any other way to give us the desired benefits without locking it down that much?

Just raising my 2C

**Comment by tanner0101** [comment]
@0xTim I could reimplement the (arguably hacky) code to support custom identifier keys, but that would only work for SQL databases. MongoDB requires that the identifier key be `_id`. My concern here is allowing people to build their app in a way that is not compatible with all of Fluent's supported drivers. If we could find a way to make it clear that identifiers with custom keys should be used sparingly I would feel more comfortable. But even then it's still unfortunate to need the hacks built in for something we recommend not using. 

> Making models only work with the ID name of id will make it impossible for some existing databases to be Fluent compatible.

It's worth mentioning that using Fluent with existing databases has many other problems, too. Fluent makes a lot of assumptions about what the database should look like. A lower level ORM like SQLKit is a much better tool for these situations IMO. 

> It also complicates migrating from Fluent 3 to Fluent 4 for anyone who used an ID key of anything other than id.

This is a good point. Although renaming the column to `"id"` shouldn't be too difficult. 

I think that given how many issues custom identifier keys raise, we should be asking what utility they provide. I can't think of any example besides using Fluent with an existing database which is of questionable utility. Every other use case of custom identifiers I can think of would be better suited by a unique `@Field`, e.g.,:

```swift
@ID(key: .id) var id: UUID?
@Field(key: "username") var username: String
```

**Comment by Joannis** [comment]
I +1 on what Tanner said. Worst case scenario you'll need to support schema migration, in which case you wouldn't even worry about MongoDB which wasn't supported in Fluent 3.

**Comment by tanner0101** [comment]
These changes are now available in [1.0.0-beta.5](https://github.com/vapor/fluent-kit/releases/tag/1.0.0-beta.5)

**Pull request merged**
