### PR TITLE
Typesafe schema builder

### PR DESCRIPTION
**Pull request by GreatApe**
With this PR a new, type-safe schema builder is introduced, which relies on key paths. Using this, and given a model:

```Swift
final class User: Model, Content {
    static let schema = "users"

    @ID(key: "id")
    var id: Int?

    @Field(key: "username")
    var username: String

    @Field(key: "password_hash")
    var passwordHash: String

    @Field(key: "category")
    var category: String?

    @Timestamp(key: "created_at", on: .create)
    var createdAt: Date?

    @Parent(key: "group_id")
    var group: Group

    @OptionalParent(key: "admin_group_id")
    var adminGroup: AdminGroup?
}
```

we can now make the schema like this:

```Swift
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.schema(User.self)
            .id(\.$id, auto: true)
            .field(\.$username)
            .field(\.$passwordHash)
            .field(\.$category)
            .timestamp(\.$createdAt)
            .parent(\.$group, references: \.$id)
            .parent(\.$adminGroup)
            .foreignKey(\.$adminGroup, references: \$.id, onDelete: .cascade, onUpdate: .cascade)
            .unique(on: \.$username)
            .create()
    }
```

- The schema builder detects the datatypes (with a small number of exceptions, which includes Enum). 
- It also detects if the field is required and adds the `.required` constraint if that is the case. 
- Timestamp fields are supported
- For parent fields, it detects the foreign schema and if you use the version with `references:` then it will also add a foreign key constraint to the _field_.
- It detects if a parent field is an `OptionalParent` or not.
- A foreign key constraint can also be added to the schema, which is done for `adminGroup` above.
- Uniqueness constraints are supported

Note that it would be possible to use the name `field` also for `id`, `parent` and `timestamp` but it might make syntax completion overwhelming.

Note that while the `unique` method supports variadic arguments, they all need to point to the same type of field. If `AnyField` was public we might be able to get around that with something like

```Swift
public func unique(on keyPaths: KeyPath<M, AnyField>...) -> Self {
    let model = M()
    schema.constraints.append(.unique(fields: keyPaths.map { .string(model[keyPath: $0].key) }))
    return self
}
```

### CODE REVIEW

**Comment by MihaelIsaev** [comment]
@GreatApe Migration with keypaths are not good for long perspective. I realized that after trying to do the same what you did a few week ago in my fork 🙂

**Comment by GreatApe** [comment]
No? In what way?

**Comment by GreatApe** [comment]
I still keep two manual methods

```Swift
    /// Adds an manually defined  field with the given parameters
    public func defineField(name: DatabaseSchema.FieldName, dataType: DatabaseSchema.DataType, constraints: [DatabaseSchema.FieldConstraint]) -> Self {
        schema.createFields.append(.definition(name: name, dataType: dataType, constraints: constraints))
        return self
    }

    /// Adds an manually defined custom  field
    public func defineField(custom: Any) -> Self {
        schema.createFields.append(.custom(custom))
        return self
    }
```

**Comment by 0xTim** [comment]
So the issue with this is that in any real system when it comes to removing columns or renaming them or renaming tables etc this all breaks down horribly. This is why a lot of the type safe stuff has been changed in Fluent 4. 

Now I don't necessarily agree with it all but those are the reasons that Tanner has specified. I've been playing around with static versioned strings as a way to bring some type safety back as a compromise and using the existing APIs, similar to how things were done in the Vapor 2 days. I would personally like to see some helpers or syntactic sugar added for simple projects but not sure pushing everyone down the key path route and then having to sort it out when it invariably breaks in the future will be a good step forward, especially whilst Swift can't work it out for itself.

**Comment by GreatApe** [comment]
@0xTim Thanks for the reply Tim. I understand, sort of. If you have changed your model you can't then use that keypath anymore, right? But isn't that only relevant for `deleteField`? I can't see how that could come into play for the methods where you specify the fields, or am I misunderstanding what schemas are for?

A nice compromise would seem to be to allow deletion(and renaming, which I didn't know existed) to be stringly typed, and the definition ones to use keypaths. Would there be any problems with that approach?

**Comment by 0xTim** [comment]
Sorry for the delay! So to demonstrate the issue, let's imagine two developers - Alice and Bob - working on the same project.

Alice is current working on a model, `User`. She builds the migration like so (I'll use Vapor 3 syntax as I can remember that off the top of my head, but the pricipal applies for a Vapor 4 typesafe schema builder):

```swift
Database.create(User.self).flatMap { builder in
  // ...
  builder.field(for: \.address)
  // ...
}
```

She runs the migration and all is good and it gets deployed to production. At some point in the future, she wants to rename a column, from `address` to `homeAddress`. So she creates a new migration:

```swift
Database.update(User.self).flatMap { builder in
  // Update the address column. This has to use strings since the address property no longer exists
}
```

Now since the original migration was `builder.field(for: \.address)` that also has to be updated since that property no longer exists. So that either becomes `builder.field(for: \.homeAddress` or has to be written as a string (which could be mistyped). Since Alice (and production) have already run the `User` migration, they will never run that migration again so it doesn't really matter.

At some point in the future, Bob comes along to the project and gets set up with a fresh development environment, including running all the migrations. If the type safe stuff is used, the `User` migration will create the table with the `homeAddress` property and then when it comes to the update address migration will fail. Now if you scale that up to a large production app where columns and tables are constantly changing, you end up just needing strings everywhere anyway. Does that make sense?

PS: I _hate_ the stringly typed stuff in Fluent but there isn't really a way around it and I fully understand the reasons for it. I've been playing around with using versioned strings for the properties which brings back some type safety and means you only have to define the string in a single place which should cut out most of the errors. I'll write about it soon.

**Comment by GreatApe** [comment]
@0xTim @gwynne
Thank you for the detailed replies! I understand the general idea, that we can only use keypaths for things that are still present on our model class. But it seems to me that this only relevant in two cases:

- When deleting a field
and possibly:
- When renaming a column

I'm not even sure about the second one, since it seems that the way this is done is to read from one column and write into another, which wouldn't use the SchemaBuilder anyway?

In any case, wouldn't it still make sense to use keypaths when _creating_ columns? Or would you ecer want to create a column for a model you no longer have? I haven't used Fluent enough to know what it looks like in a big production project, but even my imagination is not enough to see when you would create fields for non-present models. Could you give me an example?

**Comment by 0xTim** [comment]
You want to keep a record of all migrations run, including the original migration that references columns that no longer exist. So whilst changing the original migration to update for the new name would be fine for you (since you've already executed the original migration), if someone comes to the project and tries to run all migrations from fresh they'd get an error.

This issue has cropped up again and again when people start changing models in Vapor 3 (further compounded by the default implementation of `addProperties(to:)`) which is one of the reasons it was changed.

**Comment by tanner0101** [comment]
@0xTim thank you for the in-depth explanation. I agree some helpers or at least documentation about how to do migrations in a way that doesn't repeat string literals everywhere would be nice. 

As far as this PR is concerned, I do not think key paths are the right approach for Fluent to provide for solving this problem. They have been a source of problems in Fluent 3 and removing them was intentional. Thank you @GreatApe for the contribution though. I'm happy to continue discussing other potential solutions to this problem of repeated strings in a separate issue.

**Pull request closed without merging**
