### PR TITLE
Fix multiple set bug

### PR DESCRIPTION
**Pull request by vkill**
e.g.

```
Todo.query(on: db)
    .filter(\.id == 1)
    .set(\.status, to: 2)
    .set(\.updatedAt, to: Date())
    .update()
```

### CODE REVIEW

**Comment by vkill** [comment]
Yes, I will write test cases tomorrow.

**Comment by tanner0101** [comment]
I think a better solution to this would be moving this code somewhere else:
https://github.com/vapor/fluent-kit/blob/master/Sources/FluentKit/Query/QueryBuilder.swift#L25-L29

It would make sense if the default fields were only added when the query runs _iff_ there are no fields added yet. 

That way we don't need a separate solution for specific key selection which I intend to add soon:

```swift
Todo.query(on: db)
    .filter(\.id == 1)
    .select(\.status)
    .select(\.updatedAt)
    .all()
```

**Comment by vkill** [comment]
@calebkleveter I have added some tests.

**Comment by tanner0101** [comment]
This has been fixed for a while now w/ tests added.

**Pull request closed without merging**
